name: Deploy

on:
  release:
    types: [published]

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tagName.outputs.tag }}
            
  deploy-azure:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: azure
      url: http://azure.monacloud.mvkaran.net
    
    steps:
       - name: Checkout repo
         uses: actions/checkout@v2
         
       - name: Set context from Kubeconfig
         uses: azure/k8s-set-context@v1
         with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }} 
          context: monacloud 
         id: setcontext

       - name: Get tag name
         uses: olegtarasov/get-tag@v2.1

       - name: Get new container image tag
         id: image-tag
         run: |
            echo "::set-output name=image::ghcr.io/$GITHUB_REPOSITORY:$GIT_TAG_NAME"

       - name: Deploy to Kubernetes
         uses: Azure/k8s-deploy@v1
         with:
            manifests: |
              k8s.yaml
            images: |
              ${{ steps.image-tag.outputs.image }}
    
